name: Github Actions with PHP
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # Se copia el contenido de nuestro repositorio en la MV
    steps:
      - uses: actions/checkout@v2

      - name: Validacion del composer.json y composer.lock
        run: composer validate --strict

      - name: Cache dependencias de Composer
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Instalacion de dependencias
        run: composer install --prefer-dist --no-progress

      - name: Ejecutar los tests
        run: composer run-script test
